### ISSUE TITLE
Default db:* tasks do not inherit configuration

### ISSUE THREAD

**Issue by koenpunt** [thuss/standalone-migrations#105]
The default `db:*` tasks do not inherit the standalone migration configuration.
So runtime modifications to the database configuration are not taken into account when for example running `rake db:create`.

Also, the default (and actually fixed) path for the yml config is `config/database.yml`. So I suggest in the first non-backwards compatible update to change this path as well.

A fix for this is to overload the `db:load_config` task and assign the correct values to `ActiveRecord::Base.configurations` ~~and `ActiveRecord::Migrator.migrations_paths`~~ _(I see that the latter [is already handled](https://github.com/thuss/standalone-migrations/blob/master/lib/standalone_migrations/tasks.rb#L9))_. Currently they are as follows:

``` rb
ActiveRecord::Base.configurations = Rails.application.config.database_configuration
ActiveRecord::Migrator.migrations_paths = Rails.application.paths['db/migrate'].to_a
```

Related: #104 #96

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
