### ISSUE TITLE
How is it standalone if it requires rails?

### ISSUE THREAD

**Issue by alexagranov** [thuss/standalone-migrations#106]
Here: 

https://github.com/thuss/standalone-migrations/blob/master/lib/standalone_migrations.rb#L5

**Comment by atironati** [comment]
:+1: also if you do require it maybe it should be added to the gemspec https://github.com/thuss/standalone-migrations/blob/master/standalone_migrations.gemspec#L60

**Comment by twobitlabs** [comment]
It doesn't require rails, see: https://github.com/thuss/standalone-migrations/issues/77

**Comment by alexagranov** [comment]
Responded on #77.  I added this gem to a project that had neither of 'rails' or 'railties' and right away bundler complained 'rails' was not found.  If not in gemspec, you should recommend railties in Readme.

**Comment by alexagranov** [comment]
Hi,

Here's a Gemfile for a simple Grape on Rack app after adding standalone_migrations.  No Rails.
https://gist.github.com/alexagranov/0509557c59630fcad071

Here's the Rakefile after adding standalone_migrations: 
https://gist.github.com/alexagranov/2fc23742f94f59e3319d

And then here's the error just trying to run 'rake -T':
```
rake aborted!
LoadError: cannot load such file -- rails
/Users/aagranov/.rvm/gems/ruby-2.1.5@fulfillment_layer_master/gems/standalone_migrations-2.0.4/lib/standalone_migrations.rb:5:in `require'
/Users/aagranov/.rvm/gems/ruby-2.1.5@fulfillment_layer_master/gems/standalone_migrations-2.0.4/lib/standalone_migrations.rb:5:in `<top (required)>'
/Users/aagranov/work/fulfillment_layer/Rakefile:8:in `require'
/Users/aagranov/work/fulfillment_layer/Rakefile:8:in `<top (required)>'
(See full trace by running task with --trace)
```
Explicitly adding railties to the Gemfile fixes the problem.
