### ISSUE TITLE
rake db:new_migration do not works fine with multiple databases

### ISSUE THREAD

**Issue by raul-ramirez** [thuss/standalone-migrations#107]
When i specify in file .dbx.standalone_migrations
db:
    seeds: db/dbx/seeds.rb
    migrate: db/dbx/migrate/
    schema: db/dbx/schema.rb
config:
    database: db/dbx/config.yml

and i have the exact tree that standalone_migrations expect to find, when i generate new migration with db:new_migration name=test_migration DATABASE=dbx, the file timestamp_test_migration.rb appears in db/migrate, not in db/dbx/migrate
It happens even the db/migrate do not exists. It creates the folder db/migrate. Later, all other commands expects to find the migration file in db/dbx/migrate (migrate, status, rollback etc...). But the new_migration command put the migration file in the wrong place.
I have try several things, without success.

**Comment by inyigo** [comment]
@raul-ramirez I am encountering this issue now. Any chance you found a fix?

**Comment by raul-ramirez** [comment]
No, i have this problem unresolved yet...

Raúl Jacobo Ramírez Núñez
info@raulramirez.es

**Comment by slpsys** [comment]
This still totally a problem, but it appears to be limited to `new_migration`, the Rake task. When running `new_migration` in the multi-db setup:

    marc-mbp-2:schemas marc$ rake DATABASE=events db:create
    marc-mbp-2:schemas marc$ rake DATABASE=events db:new_migration name=create_derp
          create  db/migrate/20160219002455_create_derp.rb
    marc-mbp-2:schemas marc$ rake DATABASE=events db:migrate
    marc-mbp-2:schemas marc$ rake DATABASE=events db:version
    Current version: 0

it appears to ignore the custom `migrate_dir` option, and go straight to `db/migrate`. However Rails/ActiveRecord itself seems to know about this custom directory, because if you move the file from `db/migrate` to `db/migrate/your_db`:

    marc-mbp-2:schemas marc$ mv db/migrate/20160219002455_create_derp.rb db/migrate/events/
    marc-mbp-2:schemas marc$ rake DATABASE=events db:migrate
    == 20160219002455 CreateDerp: migrating =======================================
    -- create_table(:derps)
       -> 0.0157s
    == 20160219002455 CreateDerp: migrated (0.0159s) ==============================

it runs the migration completely as expected. I assume this is because the only real task this project defines is `new_migration`, and [it doesn't seem to be worrying about the multi-db setup](https://github.com/thuss/standalone-migrations/blob/89aeb5e/lib/standalone_migrations/tasks/db/new_migration.rake).

**Comment by slpsys** [comment]
Update: this _seems_ to be a Rails issue. I spent a bunch of time messing with using the `Configurator` class to override the `db/migrate` path, but Rails kept overriding me. It looks like from inside the migration generator, [it's hardcoding "db/migrate"](https://github.com/rails/rails/blob/bb382b7aee116446518ca4ed1c6472d6b58f42b5/activerecord/lib/rails/generators/active_record/migration/migration_generator.rb#L11), and doesn't seem like it's [going out of its way to respect your overrides](https://github.com/rails/rails/blob/bb382b7aee116446518ca4ed1c6472d6b58f42b5/railties/lib/rails/generators/migration.rb#L37-L66). 

So the options appear to be patch Rails to respect overrides to `Rails.application.config.paths['db/migrate'], wrap calls to `db:new_migration` in a shell command (or put up with moving new migrations yourself, or move on.

**Comment by ankane** [comment]
Thanks for doing the research on this @slpsys. Here's how we solved it (in `Rakefile`):

```ruby
module NewMigrationPatch
  def create_migration_file
    set_local_assigns!
    validate_file_name!
    migration_template @migration_template, "#{Rails.application.config.paths['db/migrate'].first}/#{file_name}.rb"
  end
end

task :new_migration_patch do
  require "rails/generators/active_record/migration/migration_generator"
  ActiveRecord::Generators::MigrationGenerator.prepend(NewMigrationPatch)
end
task 'db:new_migration': :new_migration_patch
```

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
