### ISSUE TITLE
Accessing Rake Tasks from Another Gem

### ISSUE THREAD

**Issue by proteantech** [thuss/standalone-migrations#113]
I want to have my models and migrations in one gem and then be able to use them from another. Any suggestions on how to accomplish this? I tried a method I saw in a few other places which involves putting your rake tasks you want to expose in lib/tasks/db_tasks.rake and importing from the main Rakefile like so:

```
import "./lib/tasks/db_tasks.rake"
```

But my rake seems to hit an infinite loop when I try to use it... Just to clarify I'm initially trying to run the rake tasks from the same gem where the models/migrations are defined. I haven't even gotten to the point where I am trying to then run the migrations from another gem.

Here's a link which explains the method I was trying to use:
http://andyatkinson.com/blog/2014/06/23/sharing-rake-tasks-in-gems

UPDATE: 

This actually happens even if my Rakefile has the standard usage and this is duplicated in "db_tasks.rake":

```
require 'standalone_migrations'
StandaloneMigrations::Tasks.load_tasks
```

Contents of "lib/tasks/db_tasks.rake" are the same as the Rakefile.

Also using an older Gem version because my project is stuck at ActiveRecord 3 / Rails 3.

Gemfile.lock

```
standalone_migrations (2.1.5)
      activerecord (~> 3.2)
      railties (~> 3.2)
      rake (~> 10.0)
```

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
