### ISSUE TITLE
Doesn't work without Rails

### ISSUE THREAD

**Issue by l8nite** [thuss/standalone-migrations#114]
The tag line in the README says "Rails migrations in non-Rails (and non Ruby) projects."

However:

```
irb(main):002:0> StandaloneMigrations::Tasks.load_tasks
NoMethodError: Cannot load `Rails.application.database_configuration`:
undefined method `config' for main:Object
```

**Comment by twobitlabs** [comment]
I imagine you discovered the other issue where we talk about this but for people who stumble on this issue, here's a reference to the answer https://github.com/thuss/standalone-migrations/issues/77

**Comment by l8nite** [comment]
Thanks! I actually ended up using the 'active_record_migrations' gem instead.
