### ISSUE TITLE
Can't get migrations to dump a structure.sql with a UTF-8 client encoding

### ISSUE THREAD

**Issue by bitemyapp** [thuss/standalone-migrations#118]
It always starts with this

``` sql
--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'SQL_ASCII';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
```

Despite my config.yml mentioning utf8 for all my databases.

I think it's down to this:

https://github.com/rails/rails/blob/833b14c8f8cae2f2ad2ea31669380b51e644c7db/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L673-L678

but `SQL_ASCII` is not a safe default, `UTF-8` is much better. How do I configure standalone migrations to use a PostgreSQL connector with a UTF-8 client encoding such that that's what gets dumped to `db/structure.sql`?

**Comment by abevoelker** [comment]
Not familiar w/ this gem, but I believe Rails uses the encoding of the database you're connecting to when generating the migrations. Can you check the encoding of the database you're connected to when generating these migrations?

```
psql my_database -c 'SHOW SERVER_ENCODING'
```

**Comment by bitemyapp** [comment]
```
 server_encoding 
-----------------
 UTF8
(1 row)
```

**Comment by bitemyapp** [comment]
Your description seems to hold:

>AFAIK structure.sql is generated by shelling out to the PostgreSQL CLI tools, the Rails configuration isn't involved beyond specifying the basic connection parameters.

**Comment by bitemyapp** [comment]
Also for client_encoding:

```
 client_encoding 
-----------------
 UTF8
(1 row)
```

**Comment by abevoelker** [comment]
Hunh that is weird. Not that I don't trust your database install but you could try spinning up a Docker container that I know has UTF-8 support and running your migrations against that to verify:

```
docker run -it --rm -p 5433:5432 abevoelker/postgres:latest
PGPASSWORD=password psql -h localhost -p 5433 -U postgres
```

**Comment by abevoelker** [comment]
You could also try setting DATABASE_URL instead of using the YAML files (and making sure nothing is presently set there that might be overriding something, although unlikely)... you could use something like

```
DATABASE_URL="postgresql://user:password@localhost:5432/my_database?encoding=utf8"
```

**Comment by bitemyapp** [comment]
@abevoelker I tried the database url, it ran the migration successfully, still not dumping a structure.sql with a unicode encoding.

**Comment by abevoelker** [comment]
Well in that case `¯\_(ツ)_/¯`, maybe someone else will know

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
