### ISSUE TITLE
"rename_column" quoting default  'CURRENT_TIMESTAMP'

### ISSUE THREAD

**Issue by paulrrogers** [thuss/standalone-migrations#120]
Attempts to rename a column whose current default is already "CURRENT_TIMESTAMP" produces:

> Mysql2::Error: Invalid default value for '...': ALTER TABLE `...` CHANGE `...` `...` timestamp DEFAULT 'CURRENT_TIMESTAMP' NOT NULL

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
