### ISSUE TITLE
support for ActiveRecord 5

### ISSUE THREAD

**Issue by mrambossek** [thuss/standalone-migrations#123]
the Gemfile currently has

```
gem 'activerecord', ENV['AR'] || ["~> 4.2.5", ">= 4.2.5.1"]
gem 'railties', ENV['AR'] || ["~> 4.2.5", ">= 4.2.5.1"]
```

rails 5 is out, and with it activerecord - would be awesome if we could get an update. thanks :)

**Comment by twobitlabs** [comment]
We always welcome pull requests!

**Comment by vinhhv** [comment]
Just created a pull request for this issue, please check it out!

**Comment by twobitlabs** [comment]
Closing this issue since we now support AR 5.2.0
