### ISSUE TITLE
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove gem 'standalone_migrations' and try again.

### ISSUE THREAD

**Issue by luxious** [thuss/standalone-migrations#126]
my gemfile here

``` ruby
source 'http://gems.ruby-china.org'

ruby '2.3.0'

gem 'grape', '~> 0.16'
gem 'grape-swagger'
gem 'json'
gem 'rack-cors'
gem 'mime-types'
gem 'nokogiri'
gem 'activerecord','4.2.6'
gem 'mysql2'
gem 'standalone_migrations'

group :development do
  gem 'rake'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-rack'
  gem 'rubocop'
  gem 'better_errors'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'capybara'
  gem 'selenium-webdriver'
end
```

**Comment by sunnyrjuneja** [comment]
can confirm this problem with a simpler Gemfile

**Comment by ivanovaleksey** [comment]
The problem is still here.

**Comment by fcce** [comment]
@ivanovaleksey  run `bundle update` , it will making correct dependences

**Comment by jan** [comment]
`bundle update`fixed the issue for me.

**Comment by bjelline** [comment]
had to downgrade rake 12 to rake 10 to get it to work

**Comment by sbishep** [comment]
Same error. None of the above fixed it.

**Comment by jrochkind** [comment]
I am getting this, but I think this is perhaps an erroneous error message from bundler -- what's really going on, I think, is I was trying to use it with Rails 5.1.0.rc1, but there is no `standalone_migrations` that allows Rails 5.1. Maybe. Not totally sure.

**Comment by twobitlabs** [comment]
We now support AR 5.2.0 so closing this. Feel free to re-open if still an issue with the latest version.
