### ISSUE TITLE
Fix rake version requirement

### ISSUE THREAD

**Issue by bootstraponline** [thuss/standalone-migrations#134]
```
Bundler could not find compatible versions for gem "rake":
  In Gemfile:
    rake (>= 12.0)

    standalone_migrations (>= 5.2.1) was resolved to 5.2.1, which depends on
      rake (~> 10.0)
```

Is there a reason why rake 12 isn't supported?

**Comment by twobitlabs** [comment]
Yeah, that should be updated. Feel free to send a PR with an update and as long as the unit tests pass on travis we'll merge it and publish an update.
