### ISSUE TITLE
LoadError: cannot load such file -- standalone_migrations

### ISSUE THREAD

**Issue by angelacode** [thuss/standalone-migrations#136]
I executed the following:

> ENVIRONMENT=development bundle exec gem install standalone_migrations
> ENVIRONMENT=development bundle exec rake db:new_migration name=foo_bar_migration

I get a Load Error:

> LoadError: cannot load such file -- standalone_migrations

**Comment by efrapp** [comment]
Hi @angelacode 
Did you run `bundle install` before? I got that error too because the standalone_migration gem was not installed.

**Comment by Pysis868** [comment]
Installed via RubyGems, added require, seems to work fine.  Rails projects may need it in the Gemfile as well.

Issue is quite old.  Close?

**Comment by thuss** [comment]
Good call, going to close this issue due to age. If it's still a problem let me know and I can re-open it.

**Comment by ruanltbg** [comment]
@thuss I think it is still a problem, check https://github.com/thuss/standalone-migrations/issues/144

**Comment by WA9ACE** [comment]
I'm having the same issue as well. Just curious @ruanltbg do you have a `.bundle/config`? I'm using mine to install to `vendor/bundle` with

```
---
BUNDLE_PATH: "vendor/bundle"
```
