### ISSUE TITLE
Environment variables in db/config.yml

### ISSUE THREAD

**Issue by fernandoaleman** [thuss/standalone-migrations#139]
Is it possible to use environment variables in the `db/config.yml` file? Normally we use Rails for our apps, but we are currently maintaining a legacy PHP app. `standalone-migrations` works great in the PHP app out-of-the-box, but we'd like to be able to keep consistent with using environment variables.

We've tried all the variations below with no luck. Any suggestions?

```php
development:
  adapter: mysql2
  encoding: utf8
  database: ENV['MYSQL_DATABASE']
  username: ENV['MYSQL_USER']
  password: ENV['MYSQL_PASSWORD']
  pool: 5
  timeout: 5000
  host: ENV['MYSQL_HOST']
```

```php
development:
  adapter: mysql2
  encoding: utf8
  database: getenv('MYSQL_DATABASE')
  username: getenv('MYSQL_USER')
  password: getenv('MYSQL_PASSWORD')
  pool: 5
  timeout: 5000
  host: getenv('MYSQL_HOST')
```

```php
development:
  adapter: mysql2
  encoding: utf8
  database: ${MYSQL_DATABASE}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  pool: 5
  timeout: 5000
  host: ${MYSQL_HOST}
```

**Comment by jrochkind** [comment]
@fernandoaleman I'm not the maintainer, but I think it looks like the config file is run through ERB, so try using ERB tags. `database: <%= ENV['MYSQL_DATABASE'] %>'

**Comment by thuss** [comment]
Closing this issue since @jrochkind provided the solution.

**Comment by jaykilleen** [comment]
For anyone else that is having difficulty with this. 

I have a ruby project that uses `standalone_migrations`. I also have the `config.yml` and wanted to include environment variables like we do with rails.

The `config.yml` did not appear to run through erb as suggested above... keep in mind I might not have followed the docs probably for this gem. Anyway, I added `require 'erb'` to my file and parsed the yml config using `ERB.new(...).result` and it works. 

```
require 'erb'
Dir["#{File.dirname(__FILE__)}/../lib/**/*.rb"].each { |f| load(f) }

ENV['ENV'] ||= "development"

def db_configuration
  db_configuration_file = File.join(Application.root, 'db', 'config.yml')
  YAML.load(ERB.new(File.read(db_configuration_file)).result)
end

ActiveRecord::Base.establish_connection(db_configuration[ENV['ENV']]) if ENV['ENV'] == 'development'
```
