### ISSUE TITLE
interest in supporting Rails 6?

### ISSUE THREAD

**Issue by jrochkind** [thuss/standalone-migrations#157]
Are there any current maintainers interested in adding support for Rails 6.0?

**Comment by byt3pool** [comment]
Since Rails 6.0 was released some time ago, is there any update on this?

**Comment by marcoadkins** [comment]
I have a PR open to support this just waiting for a maintainer to merge it. https://github.com/thuss/standalone-migrations/pull/159

**Comment by lchojnowski** [comment]
@thuss will be great to see that update soon :)

**Comment by marcoadkins** [comment]
@thuss Hasn't had any activity in the last year. Not sure he is still maintaining this project.

**Comment by thuss** [comment]
Thanks for calling this to my attention, I will take a look at the PR and if it looks good get it merged and published.

**Comment by thuss** [comment]
Published version 6 of the gem, thanks again for the contribution: https://rubygems.org/gems/standalone_migrations/versions/6.0.0
