### ISSUE TITLE
Rails 7.2

### ISSUE THREAD

**Issue by rsamoilov** [thuss/standalone-migrations#184]
Hey there, do you plan to support Rails 7.2?

**Comment by thuss** [comment]
Standalone migrations is a community run project with many contributors. Send us a PR with Rails 7.2 support, put your name in the README.md as a contributor (if you like), and if the tests pass, we'll merge it and publish a new version of the gem. Thanks!

**Comment by rsamoilov** [comment]
ok, see https://github.com/thuss/standalone-migrations/pull/185. Thanks.
