### ISSUE TITLE
Support for schema_format :sql, alternate 'db/structure.sql' filenames in config?

### ISSUE THREAD

**Issue by sharplet** [thuss/standalone-migrations#57]
I'm working with a legacy DB2 database (over JDBC) which requires database-specific features, so I need to use sql type schema dumps. Would it be possible to have support for this directly in the standalone migrations config? I'm currently using the following to achieve this:

``` ruby
begin
  require 'arjdbc/jdbc/rake_tasks'
  require 'tasks/standalone_migrations'
  ActiveRecord::Base.schema_format = :sql # set dump type to sql
  ENV['DB_STRUCTURE'] = 'alt/path/to/structure.sql' # used by core AR adapters to provide an alternate path to 'db/structure.sql'
rescue
  puts "gem install standalone_migrations to get db:migrate:* tasks! (Error: #{e})"
end
```

A potential solution:

``` yaml
db:
  seeds: ...
  migrate: ...
  schema_format: sql
  schema: path/to/structure.sql
```

In this case if the format is set to sql, I'm thinking that behind the scenes the `ENV['DB_STRUCTURE']` var would be set to the value for `schema`.

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
