### ISSUE TITLE
Rails dependancy

### ISSUE THREAD

**Issue by petrjanda** [thuss/standalone-migrations#77]
Hello,

we had included the gem in one of our gems, which is supposed to work completely framework agnostic, although in source code i see the 'rails' is actually required. 

See here https://github.com/thuss/standalone-migrations/blob/v2.0.6/lib/standalone_migrations.rb#L5

Is that really an intention?

**Comment by alexagranov** [comment]
Ok, so while technically correct that rails is not required if railties is being used, one must have at least one of either 'rails' or 'railties' loaded.  You should clarify that in the Readme.
