### ISSUE TITLE
Custom migration folder and seeds file ignored

### ISSUE THREAD

**Issue by morcmarc** [thuss/standalone-migrations#79]
Did anyone else experienced any issues with custom paths? I just tried to put the new multiple database feature in action and noticed the custom migrate folder is ignored. Here is the output for the paths from `lib/standalone_migrations/tasks.rb`:

{"app"=>["app"], "app/assets"=>["app/assets"], "app/controllers"=>["app/controllers"], "app/helpers"=>["app/helpers"], "app/models"=>["app/models"], "app/mailers"=>["app/mailers"], "app/views"=>["app/views"], "lib"=>["lib"], "lib/assets"=>["lib/assets"], "lib/tasks"=>["lib/tasks"], "config"=>["config"], "config/environments"=>["config/environments"], "config/initializers"=>["config/initializers"], "config/locales"=>["config/locales"], "config/routes"=>["config/routes.rb"], "db"=>["db"], **"db/migrate"=>["db/migrate"], "db/seeds"=>["db/seeds.rb"],** "vendor"=>["vendor"], "vendor/assets"=>["vendor/assets"], "vendor/plugins"=>["vendor/plugins"], *\* "config/database"=>["db/config_mydb1.yml"] *\* , "config/environment"=>["config/environment.rb"], "lib/templates"=>["lib/templates"], "log"=>["log/local.log"], "public"=>["public"], "public/javascripts"=>["public/javascripts"], "public/stylesheets"=>["public/stylesheets"], "tmp"=>["tmp"]}

It seems only `config/database` is being appended. A possible solution: https://gist.github.com/morcmarc/5318075

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
