### ISSUE TITLE
Rake db:test:prepare no longer works

### ISSUE THREAD

**Issue by delwaterman** [thuss/standalone-migrations#82]
Running db:test:prepare no longer works with activerecord-3.1. Traced the issue to the definition of the rake tasks:

```
# activerecord/lib/active_record/railties/databases.rake
namespace :db do
  namespace :test do
    ...
    # line 481
    task :prepare => 'db:abort_if_pending_migrations' do
      if defined?(ActiveRecord) && !ActiveRecord::Base.configurations.blank?
         db_namespace[{ :sql  => 'test:clone_structure', :ruby => 'test:load' }[ActiveRecord::Base.schema_format]].invoke
     end
  end
end
```

Because you bypass the ActiveRecord::Base.configurations and manually establish the connection, this task no longer executes the tasks that actually loads the schema.

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
