### ISSUE TITLE
Add support for active_record configuration

### ISSUE THREAD

**Issue by davidinjc** [thuss/standalone-migrations#98]
Hi,

It'd be great if there's a way to throw in active_record configuration options. For instance, my app runs in a shared database, so I want to set the config.active_record.schema_migrations_table_name to have my own migrations_schema table. 

I poked around a bit and did not see an obvious place for it. And without an extensive knowledge of how Rails gets wired, I'm not sure what'd be the best approach.

Thanks!

**Comment by twobitlabs** [comment]
Closing due to the age of this issue.
